### PR TITLE
Adding cargo tests for window

### PR DESCRIPTION
**Pull request by DanTheColoradan**
Attempts to address issue #981.

Looking for lots of feedback as I've never written unit tests before.

Expect lots of comments and lots of commits.

### CODE REVIEW

**Comment by xaviershay** [comment]
left you lots of feedback :)

**Comment by DanTheColoradan** [comment]
@xaviershay, thank you so much. Gonna work through your comments now. So very very helpful.

**Comment by DanTheColoradan** [comment]
How's Australia btw? Seems like there are quite a few good / friendly programmers there :)

**Comment by xaviershay** [comment]
there are, I'm an expat though, been in SF 4 years :)

**Comment by DanTheColoradan** [comment]
Bah! Expats! At least you could've gone to a more socialist country ;-) *semi ignorant American statement*

Gonna work more tomorrow on this. Too much ethanol...

Thanks again @xaviershay.

**Comment by bvssvni** [comment]
@DanTheColoradan These tests are not useful. They simply store data. Thanks for the effort, though. I appreciate it!

There is not much to test in the core, except for the game loop maybe, but it has been tested in practice and reviewed a lot. It uses a timer so it's hard to write a unit test for it.

Closing.

**Pull request closed without merging**
